ignored_names: # Lowercase, or we'll all die
  - ':'
  - 'and'
  - 'by proxy'
  - 'da'
  - 'deviantart'
  - 'discorapp.com'
  - 'discord chat'
  - 'discord'
  - 'discord username'
  - 'discordapp.com'
  - 'ebay'
  - 'etsy'
  - 'fa'
  - 'facebook'
  - 'furaffinity'
  - 'furry amino:'
  - 'fursuit'
  - 'instagram'
  - 'join.me'
  - 'new account'
  - 'newgrounds:'
  - 'nsfw'
  - 'on discord'
  - 'on furry amino:'
  - 'on twitter'
  - 'orginal stickers:'
  - 'other social media'
  - 'patreon'
  - 'payment done with paypal.'
  - 'paypal.com'
  - 'pixiv:'
  - 'sticker tracer'
  - 't.me'
  - 'telegram app stickers'
  - 'telegram application'
  - 'telegram channel'
  - 'telegram updates:'
  - 'telegram'
  - 'th'
  - 'traced stickers :'
  - 'tumblr'
  - 'twitter'

ignored_where: # Lowercase, or we'll all die
  - 'deviant art'
  - 'deviantart'
  - 'discord'
  - 'email'
  - 'etsy'
  - 'facebook'
  - 'fur affinity'
  - 'furaffinity'
  - 'furaffinity.net'
  - 'furbuy'
  - 'furry amino'
  - 'gmail'
  - 'instagram'
  - 'paypal'
  - 'secondlife'
  - 'telegram'
  - 'toyhouse'
  - 'trello'
  - 'tumblr'
  - 'twitter'
  - 'www.deviantart.com'
  - 'www.picarto.com'
  - 'www.thedealersden.com'
  - 'www.tumblr.com'
  - 'www.twitter.com'

ignored_where_lines: # Lowercase, or we'll all die
  - 'also'
  - "anthrocon dealer's den"
  - 'approached via notes on furaffinity'
  - "further confusion 2017 - dealer's table (purchase transaction)"
  - 'anthrocon'
  - 'business however was conducted over discord.'
  - 'business via telegram'
  - 'dealers den at arizona fur con, mesa, az'
  - 'discord / art commissions discord'
  - 'discord message'
  - 'fa?'
  - 'furlandia 2018'
  - 'https://discord.com/'
  - 'https://www.reddit.com/'
  - 'ifc 2011'
  - 'indyfurcon 2011'
  - 'megaplex 2017 - artist alley'
  - 'midwest fur fest dealers room/square'
  - 'now moved to'
  - 'post-fc2017 - telegram conversation (idea submitted)'
  - 'saboten con 2012 - https://www.sabotencon.com/'
  - 'telegram, email.'
  - 'the website does not seem to exist anymore'
  - 'through fa, then through discord dms'

removed_text_general: # Case-sensitive!
  - '(abandoned)'
  - '(active)'
  - '(Artist)'
  - '(available via their FA)'
  - '(Commission Non-Delivery)'
  - '(Deactivated)'
  - '(defunct as of Aug 2020)'
  - '(Deleted and purged)'
  - '(deleted)'
  - '[Followup]'
  - '(gore warning)'
  - '(just in case)'
  - '(new account)'
  - '(now deactivated)'
  - '(other aliases)'
  - '(private)'
  - '(Queued for Deletion)'
  - '(she got herself banned)'
  - '(since deactivated/no longer exists)'
  - '(Store Envy link Defunct)'
  - '- Deleted and Purged'
  - 'On Discord, user deleted account.'

ignored_tags:
  - '2016'
  - '2019'
  - '2020'
  - 'adoptable'
  - 'animation'
  - 'archive:2011'
  - 'archive:2012'
  - 'archive:2013'
  - 'archive:2014'
  - 'archives:2011'
  - 'art trade'
  - 'beware'
  - 'business organization'
  - 'caution'
  - 'chargeback'
  - 'closed species'
  - 'commission'
  - 'commissioner'
  - 'company'
  - 'contest'
  - 'double sale'
  - 'etsy'
  - 'frequent name changes'
  - 'goods'
  - 'inactiveaccount'
  - 'items'
  - 'nsfw'
  - 'other'
  - 'patreon'
  - 'plush'
  - 'repost'
  - 'resolved'
  - 'sculpture'
  - 'tracing'
  - 'trade'
  - 'writer'
  - 'ych'

non_name_tags:
  - 'art theft'
  - 'artist'
  - 'client'
  - 'fursuit'
  - 'kigurumi'
  - 'musician'
  - 'scammer'
