---
ignored_names_ci:
  - ':'
  - 'and'
  - 'by proxy'
  - 'da'
  - 'deviantart'
  - 'discorapp.com'
  - 'discord chat'
  - 'discord username'
  - 'discord'
  - 'discordapp.com'
  - 'ebay'
  - 'etsy'
  - 'fa'
  - 'facebook'
  - 'furaffinity'
  - 'furry amino:'
  - 'fursuit'
  - 'instagram'
  - 'join.me'
  - 'new account'
  - 'newgrounds:'
  - 'nsfw'
  - 'on discord'
  - 'on furry amino:'
  - 'orginal stickers:'
  - 'other social media'
  - 'patreon'
  - 'payment done with paypal.'
  - 'paypal.com'
  - 'pixiv:'
  - 'sticker tracer'
  - 't.me'
  - 'telegram app stickers'
  - 'telegram application'
  - 'telegram channel'
  - 'telegram updates:'
  - 'telegram'
  - 'th'
  - 'traced stickers :'
  - 'trello with an insane backlog:'
  - 'tumblr'
  - 'tumblr:'
  - 'twitter'

ignored_where_ci:
  - 'deviant art'
  - 'deviantart'
  - 'discord'
  - 'email'
  - 'etsy'
  - 'facebook'
  - 'fur affinity'
  - 'furaffinity'
  - 'furaffinity.net'
  - 'furbuy'
  - 'furry amino'
  - 'gmail'
  - 'instagram'
  - 'paypal'
  - 'secondlife'
  - 'telegram'
  - 'toyhouse'
  - 'trello'
  - 'tumblr'
  - 'twitter'
  - 'www.deviantart.com'
  - 'www.picarto.com'
  - 'www.thedealersden.com'
  - 'www.tumblr.com'
  - 'www.twitter.com'

ignored_where_lines_ci:
  - "anthrocon dealer's den"
  - "further confusion 2017 - dealer's table (purchase transaction)"
  - 'also'
  - 'ane con 2018'
  - 'anthrocon'
  - 'approached via notes on furaffinity'
  - 'business however was conducted over discord.'
  - 'business via telegram'
  - 'dealers den at arizona fur con, mesa, az'
  - 'discord / art commissions discord'
  - 'discord message'
  - 'fa?'
  - 'furlandia 2018'
  - 'https://discord.com/'
  - 'https://www.reddit.com/'
  - 'ifc 2011'
  - 'indyfurcon 2011'
  - 'megaplex 2017 - artist alley'
  - 'midwest fur fest dealers room/square'
  - 'now moved to'
  - 'on twitter and tumblr'
  - 'post-fc2017 - telegram conversation (idea submitted)'
  - 'saboten con 2012 - https://www.sabotencon.com/'
  - 'telegram, email.'
  - 'the website does not seem to exist anymore'
  - 'through fa, then through discord dms'

removed_text_general:
  - "(Can't link)"
  - ' (Still trying to trade their dainty) Moved to '
  - '(Abandoned)'
  - '(Account I did business with.)'
  - '(Account refund was requested from.)'
  - '(Artist)'
  - '(Commission Non-Delivery)'
  - '(DA has been closed since last contact)'
  - '(Deactivated account)'
  - '(Deactivated)'
  - '(Deleted and purged)'
  - '(IB - consider NSFW)'
  - '(Main Tumblr)'
  - '(NSFW FA)'
  - '(NSFW GALLERY)'
  - '(NSFW Patreon)'
  - '(NSFW Tumblr)'
  - '(New Twitter)'
  - '(Old Twitter)'
  - '(Queued for Deletion)'
  - '(Store Envy link Defunct)'
  - '(abandoned)'
  - '(active but not posting)'
  - '(active)'
  - '(apparently abandoned)'
  - '(available via their FA)'
  - '(banned)'
  - '(defunct as of Aug 2020)'
  - '(deleted)'
  - '(disabled)'
  - '(gore warning)'
  - '(inactive)'
  - '(just in case)'
  - '(new account)'
  - '(now deactivated)'
  - '(old account)'
  - '(other aliases)'
  - '(private)'
  - '(she got herself banned)'
  - '(the only existed account as I know and now disabled)'
  - '- Deleted and Purged'
  - 'DeviantART (x3) - '  # Where prefix
  - 'DeviantART Group - '  # Where prefix
  - 'Do not put "Twitter"/ "Furaffinity" / "Instagram".  Put a URL such as https://twitter.com/Artists_Beware'  # Should get fixed on AB!
  - 'FurAffinity (x3) - '  # Where prefix
  - 'List all known USERNAMES here.  Doxxing is NOT permitted.'  # Should get fixed on AB!
  - 'NSFW Tumblr:'
  - 'New:'
  - 'On Discord, user deleted account.'
  - 'Telegram communications: '
  - 'Toyhouse:'
  - 'Trello List:'
  - 'Twitch:'
  - 'WHERE:'
  - 'Website:'
  - '[Followup]'
  - 'nsfw art featured here:'

ignored_tags:
  - '2016'
  - '2019'
  - '2020'
  - 'adoptable'
  - 'animation'
  - 'archiev:2018'  # Should get fixed on AB!
  - 'archive:2011'
  - 'archive:2012'
  - 'archive:2013'
  - 'archive:2014'
  - 'archive:2015'
  - 'archive:2016'
  - 'archive:2017'
  - 'archive:2018'
  - 'archives:2011'  # Should get fixed on AB!
  - 'archives:2014'  # Should get fixed on AB!
  - 'art trade'
  - 'beware'
  - 'business organization'
  - 'caution'
  - 'chargeback'
  - 'closed species'
  - 'commission'
  - 'commissioner'
  - 'company'
  - 'contest'
  - 'double sale'
  - 'etsy'
  - 'frequent name changes'
  - 'goods'
  - 'inactiveaccount'
  - 'items'
  - 'nsfw'
  - 'other'
  - 'patreon'
  - 'plush'
  - 'repost'
  - 'resolved'
  - 'sculpture'
  - 'tracing'
  - 'trade'
  - 'writer'
  - 'ych'

non_name_tags:
  - 'art theft'
  - 'artist'
  - 'client'
  - 'fursuit'
  - 'kigurumi'
  - 'musician'
  - 'scammer'
  - 'impersonation'
